### ISSUE TITLE
About jvm parameter settings

### ISSUE THREAD

**Issue by zkj1374960803** [fabric8io-images/run-java-sh#110]
I encountered a problem like this.
When I add the following configuration,the start of the program becomes unusually slow.
>  resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: 50m
              memory: 256Mi

When I change the limits cpu to 2,startup time became normal.
After comparison, I found a difference.When limits cpu equest to 1,the jvm parameters are as follows.
`-XX:ParallelGCThreads=1 -XX:ConcGCThreads=1 -Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -XX:CICompilerCount=2 `
When limits cpu equest to 2,the jvm parameters are as follows.
`-XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -XX:CICompilerCount=2`
I found this code in [run-java.sh](https://github.com/fabric8io-images/run-java-sh/blob/master/fish-pepper/run-java-sh/fp-files/run-java.sh) line 418.
Why do you want to add these four parameters, and do they have any relationship?
I speculate that the slow startup is related to the `-Djava.util.concurrent.ForkJoinPool.common.parallelism` parameter, but I read the official information, and there is no clear description.

**Comment by rhuss** [comment]
These four parameters are thread parameters and typically initialized with the number of all cores available on a machine. Since older Java's don't read the number of cores properly for a process running in a container (but see also threads from the host machine), the default is far too large when using constraints. 

So I guess the behavior that you see would be the same when you would run the process on a 1 core machine. But I'm not an expert on these options and there might better ways to tune it. 

However, maybe the best thing to commit setting the corresponding environment variables and let the JVM decide. New JVM (starting with some higher patch level for Java 8) already know how to size the defaults in a container based system.

btw, I'm not sure how the resource declaration above is reflected in run-java.sh to set the corresponding parameters ...
