### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by SlawomirLeski** [fabric8io-images/run-java-sh#114]
Is this project still active, and new java versions will be added?

**Comment by rhuss** [comment]
I'm afraid there is not much momentum on this repo anymore. This is probably due to the fact that modern Java JVMs play much nicer with containers than older Java 8 JVMs so there is probably no need for such a starter script anymore.

I would say this repo and the script are in maintenance mode (i.e. I don't have any spare cycles to keep care of it rigorously).

Happy if someone else wants to pick it up and also happy to aid in any transition.

**Comment by SlawomirLeski** [comment]
ok, thanks for the answer.
